from enum import Enum

import environ

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    USE_PROXY=(bool, False),
    HEADLESS_SELENIUM_PARSERS=(bool, True)
)

DEBUG = env('DJANGO_DEBUG')
USE_PROXY = env('USE_PROXY')
HEADLESS_SELENIUM_PARSERS = env('HEADLESS_SELENIUM_PARSERS')

FACEBOOK_SCREENSHOTS_DIR = env('FACEBOOK_SCREENSHOTS_DIR')
FACEBOOK_PID_PATH = env('FACEBOOK_PID_PATH')

OK_PID_PATH = env('OK_PID_PATH')
OK_PROXY_IP = env('OK_PROXY_IP')
OK_PROXY_PORT = env('OK_PROXY_PORT')
OK_SCREENSHOTS_DIR = env('OK_SCREENSHOTS_DIR')

TIKTOK_PROXY_IP = env('TIKTOK_PROXY_IP')
TIKTOK_PROXY_PORT = env('TIKTOK_PROXY_PORT')
TIKTOK_SCREENSHOTS_DIR = env('TIKTOK_SCREENSHOTS_DIR')
TIKTOK_PID_PATH = env('TIKTOK_PID_PATH')
TIKTOK_PARSER_LOG_FILE = env('TIKTOK_PARSER_LOG_FILE')

SELENIUM_WORKER_PROXY_IP = env('SELENIUM_WORKER_PROXY_IP')
SELENIUM_WORKER_PROXY_PORT = env('SELENIUM_WORKER_PROXY_PORT')
SELENIUM_WORKER_PID_PATH = env('SELENIUM_WORKER_PID_PATH')
RABBIT_HOST = env('RABBIT_HOST')


class AccessStatus(Enum):
    success = 'success'
    fail = 'fail'

    def __eq__(self, other):
        return self.value == other

    def __str__(self):
        return self.value
